// PR Workflow Orchestrator - handles end-to-end PR creation
import { GitHubMcpClient } from './github';
import { GitClient } from './git';
import { ModernizationPlan, TransformResult, Logger, createLogger } from '@necro/common';
import path from 'node:path';
import { readFile } from 'node:fs/promises';

export interface PRWorkflowOptions {
  owner: string;
  repo: string;
  repoPath: string;
  plan: ModernizationPlan;
  transform: TransformResult;
  prDescription: string;
  roadmap?: string;
  githubToken?: string;
  baseBranch?: string;
  logger?: Logger;
}

export interface PRWorkflowResult {
  prUrl: string;
  prNumber: number;
  branchName: string;
  filesUpdated: number;
}

export class PRWorkflowOrchestrator {
  private readonly github: GitHubMcpClient;
  private readonly logger: Logger;

  constructor(githubToken?: string, logger?: Logger) {
    this.github = new GitHubMcpClient({ token: githubToken });
    this.logger = logger ?? createLogger('info');
  }

  async createModernizationPR(options: PRWorkflowOptions): Promise<PRWorkflowResult> {
    const {
      owner,
      repo,
      repoPath,
      transform,
      prDescription,
      roadmap,
      baseBranch = 'main',
    } = options;
    const plan = options.plan;

    this.logger.info(`Starting PR workflow for ${owner}/${repo}`);

    // Generate unique branch name
    const timestamp = Date.now();
    const branchName = `necro/modernization-${timestamp}`;

    try {
      // Step 1: Create local branch and commit changes
      const git = new GitClient({ repoPath, logger: this.logger });
      
      this.logger.info(`Creating local branch: ${branchName}`);
      await git.createBranch(branchName);
      
      this.logger.info('Staging all changes');
      await git.stageAll();
      
      const commitMessage = [
        '🔮 Necro-Engine: Automated Modernization',
        '',
        `Applied ${plan.tasks.length} modernization tasks`,
        `Modified ${transform.modifiedFiles.length} files`,
        '',
        'Tasks completed:',
        ...plan.tasks.slice(0, 5).map(t => `- ${t.title}`),
        plan.tasks.length > 5 ? `... and ${plan.tasks.length - 5} more` : '',
      ].filter(Boolean).join('\n');
      
      this.logger.info('Committing changes');
      await git.commit(commitMessage);
      
      // Step 2: Push branch to remote
      this.logger.info(`Pushing branch to origin`);
      await git.push(branchName);
      
      // Step 3: Get regression ghost (top contributor)
      let ghostLine = '';
      try {
        const topAuthor = await git.getTopAuthor();
        if (topAuthor) {
          ghostLine = `\n\n---\n\n_👻 Regression Ghost: ${topAuthor.name} <${topAuthor.email}>_\n_Original maintainer's style preserved in modernization_`;
        }
      } catch (error) {
        this.logger.warn('Could not determine top author for regression ghost');
      }
      
      // Step 4: Create pull request
      const prBody = [
        prDescription,
        ghostLine,
        '',
        '## 📋 Roadmap',
        '',
        roadmap || '_Roadmap not generated_',
        '',
        '---',
        '',
        '**Generated by [Necro-Engine](https://github.com/necro-engine/necro-engine)** 🔮',
        '',
        '_This PR was automatically created by AI-powered code modernization._',
      ].filter(Boolean).join('\n');
      
      this.logger.info('Creating pull request on GitHub');
      const pr = await this.github.createPullRequest(owner, repo, {
        title: '🔮 Necro-Engine: Automated Code Modernization',
        head: branchName,
        base: baseBranch,
        body: prBody,
        draft: false,
      });
      
      this.logger.info(`Pull request created: ${pr.html_url}`);
      
      return {
        prUrl: pr.html_url,
        prNumber: pr.number,
        branchName,
        filesUpdated: transform.modifiedFiles.length,
      };
    } catch (error) {
      this.logger.error(`PR workflow failed: ${(error as Error).message}`);
      throw error;
    }
  }

  async createModernizationPRForRemote(options: PRWorkflowOptions): Promise<PRWorkflowResult> {
    const {
      owner,
      repo,
      transform,
      prDescription,
      roadmap,
      baseBranch = 'main',
    } = options;

    this.logger.info(`Starting remote PR workflow for ${owner}/${repo}`);

    // Generate unique branch name
    const timestamp = Date.now();
    const branchName = `necro/modernization-${timestamp}`;

    try {
      // Step 1: Create remote branch
      this.logger.info(`Creating remote branch: ${branchName}`);
      await this.github.createBranch(owner, repo, branchName, baseBranch);
      
      // Step 2: Update files via GitHub API
      this.logger.info(`Updating ${transform.modifiedFiles.length} files`);
      let filesUpdated = 0;
      
      for (const filePath of transform.modifiedFiles) {
        try {
          // Get current file content and SHA
          const fileInfo = await this.github.getFileContent(owner, repo, filePath, baseBranch);
          const currentContent = Buffer.from(fileInfo.content, 'base64').toString('utf-8');
          
          // Read new content from local transform
          const newContent = await readFile(path.join(options.repoPath, filePath), 'utf-8');
          
          // Update file if changed
          if (currentContent !== newContent) {
            await this.github.updateFile(
              owner,
              repo,
              filePath,
              newContent,
              `Update ${filePath}`,
              branchName,
              fileInfo.sha
            );
            filesUpdated++;
          }
        } catch (error) {
          this.logger.warn(`Failed to update ${filePath}: ${(error as Error).message}`);
        }
      }
      
      // Step 3: Create pull request
      const prBody = [
        prDescription,
        '',
        '## 📋 Roadmap',
        '',
        roadmap || '_Roadmap not generated_',
        '',
        '---',
        '',
        '**Generated by [Necro-Engine](https://github.com/necro-engine/necro-engine)** 🔮',
        '',
        '_This PR was automatically created by AI-powered code modernization._',
      ].filter(Boolean).join('\n');
      
      this.logger.info('Creating pull request on GitHub');
      const pr = await this.github.createPullRequest(owner, repo, {
        title: '🔮 Necro-Engine: Automated Code Modernization',
        head: branchName,
        base: baseBranch,
        body: prBody,
        draft: false,
      });
      
      this.logger.info(`Pull request created: ${pr.html_url}`);
      
      return {
        prUrl: pr.html_url,
        prNumber: pr.number,
        branchName,
        filesUpdated,
      };
    } catch (error) {
      this.logger.error(`Remote PR workflow failed: ${(error as Error).message}`);
      throw error;
    }
  }
}
